# Numpy

### Using arange(start, stop, step) 
Functions generate a sequence of numbers, starting from start, ending at stop (exclusive), with a step size of step

In [1]:
import numpy as np
# Example: Generate numbers from 0 to 9
x = np.arange(0, 10, 1)
print(x)

[0 1 2 3 4 5 6 7 8 9]


### Using linspace(start, stop, num)
Generates num evenly spaced values between start and stop (inclusive)

In [4]:
# Example: Generate 5 evenly spaced numbers from 0 to 10
y = np.linspace(0, 10, 5)
print(y)

[ 0.   2.5  5.   7.5 10. ]


### Using logspace(start, stop, num)
Generates num logarithmatically spaced values between powers of 10

In [5]:
# Example: Generate 4 logarithmically spaced numbers between 10^1 and 10^3
z = np.logspace(1, 3, 4)
print(z)

[  10.           46.41588834  215.443469   1000.        ]


### Using mgrid for Mesh Grid
Creates a multi-dimensional mesh grid for two dimensions. Useful for generating coordinate grids.

In [15]:
# Example: Create a 2D grid for coordinates
X, Y = np.mgrid[0:3, 0:2]
print("Mgrid example (X):", X)
print("Mgrid example (Y):", Y)

Mgrid example (X): [[0 0]
 [1 1]
 [2 2]]
Mgrid example (Y): [[0 1]
 [0 1]
 [0 1]]


### Using diag() for Diagonal Matrices
Extracts the diagonal of a matrix or creates a diagonal matrix

In [11]:
# Example: Create a diagonal matrix
diag_matrix = np.diag([1, 2, 3])
print("Diagonal matrix example:")
diag_matrix

Diagonal matrix example:


array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

### Generating random data with random
Few ways to generate random arrays

In [18]:
# Example: Create a 2x3 matrix of random values between 0 and 1
rand_array = np.random.rand(2, 3)
print("Random array example:", rand_array)

# Example: Create a 2x3 matrix of normally distributed random numbers
randn_array = np.random.randn(2, 3)
print("Random normal distribution example:", randn_array)

# Random array example:
# [[0.11697915 0.64027738 0.53711974]
# [0.5296738 0.23264256 0.8197505 ]]

Random array example: [[0.05041801 0.06803022 0.14013715]
 [0.75273976 0.34671736 0.6448038 ]]
Random normal distribution example: [[ 0.27797267  0.67542511 -0.61849826]
 [-0.57530096 -0.14274428 -2.10205427]]


### Creating Arrays of Zeros and Ones with zeros() and ones()
These functions create arrays filled with zeros or ones, respectively

In [20]:
# Example: Create a 2x3 array filled with zeros
zeros_array = np.zeros((2, 3))
print("Zeros array example:", zeros_array)

# Example: Create a 2x3 array filled with ones
ones_array = np.ones((2, 3))
print("Ones array example:", ones_array)

Zeros array example: [[0. 0. 0.]
 [0. 0. 0.]]
Ones array example: [[1. 1. 1.]
 [1. 1. 1.]]


### Additional example - eye(): Identify Matrix
You can also use eye() to create an Identity matrix

In [23]:
# Example: Create a 3x3 identity matrix
identity_matrix = np.eye(3)
identity_matrix

# print("Identity matrix example:", identity_matrix)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Exercise
1. Generate a 4x4 matrix of random integers between 1 and 100.
2. Calculate the sum of all elements in the matrix.
3. Find the maximum and minimum values in the matrix.
4. Replace all even numbers in the matrix with 0.
5. Find the row-wise sum of the modified matrix.
6. Transpose the matrix (swap rows and columns).

In [36]:
import numpy as np

# Step 1: Generate a 4x4 matrix of random integers between 1 and 100
matrix1 = np.random.randint(1,101, size=(4,4))
matrix1


array([[ 10,  63,  15,  71],
       [100,  59,  72,  42],
       [100,  48,  53,   8],
       [ 61,  58,  77,  56]])

In [38]:
# Step 2: Calculate the sum of all elements in the matrix 
sum = matrix1.sum()
sum

893

In [40]:
# Step 3: Find the maximum and minimum values in the matrix
max = matrix1.max()
min = matrix1.min()

max, min

(100, 8)

In [41]:
# Step 4: Replace all even numbers in the matrix with 0
matrix1[matrix1 % 2 == 0] = 0
matrix1

array([[ 0, 63, 15, 71],
       [ 0, 59,  0,  0],
       [ 0,  0, 53,  0],
       [61,  0, 77,  0]])

In [42]:
# Step 5: Find the row-wise sum of the modified matrix
row_wise_sum = np.sum(matrix1, axis=1)
row_wise_sum

array([149,  59,  53, 138])

In [43]:
# Step 6: Transpose the matrix (swap rows and columns)
matrix1.T

array([[ 0,  0,  0, 61],
       [63, 59,  0,  0],
       [15,  0, 53, 77],
       [71,  0,  0,  0]])

### Adding Scalars to Arrays
Can add a scalar to an array, and NumPy will broadcast the scalar to all elements of the array 

In [44]:
arr = np.array([1,2,3,4,5])
result = arr + 19
result

array([20, 21, 22, 23, 24])

### Broadcasting with 1D and 2D Arrays
Can even broadcast a 1D array to a 2D array

In [46]:
arr1 = np.array([1,2,3])
arr2 = np.array([[10,20,30], [100, 200, 300]])
result = arr1 + arr2
result

array([[ 11,  22,  33],
       [101, 202, 303]])